package dev.dumbnavigator;

import android.annotation.SuppressLint;
import android.content.Context;
import android.graphics.Color;
import android.net.Uri;
import android.webkit.CookieManager;
import android.webkit.JavascriptInterface;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.Arrays;
import java.util.Locale;

@SuppressLint("SetJavaScriptEnabled")
public final class ChromiumEngine extends WebView {
    public interface Host { void onUrl(String url); void onTitle(String title); void onProgress(int progress); void onPublish(String domain,String html,boolean wildcard); }
    private final Host host; private final ArrayDeque<String> back=new ArrayDeque<>(); private final ArrayDeque<String> forward=new ArrayDeque<>(); private String current="dumb://uuu.une.developeit.dev/";
    public ChromiumEngine(Context c,Host h){super(c);host=h;configure();}
    private void configure(){setBackgroundColor(Color.rgb(10,14,22));setOverScrollMode(OVER_SCROLL_NEVER);setLayerType(LAYER_TYPE_HARDWARE,null);WebSettings s=getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setLoadsImagesAutomatically(true);s.setBlockNetworkImage(true);s.setBlockNetworkLoads(true);s.setMediaPlaybackRequiresUserGesture(false);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);s.setSupportZoom(false);s.setUseWideViewPort(true);s.setLoadWithOverviewMode(false);s.setTextZoom(100);s.setCacheMode(WebSettings.LOAD_NO_CACHE);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setUserAgentString(s.getUserAgentString()+" dumbNavigator/1.0 Chromium-Internal");CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(this,false);addJavascriptInterface(new CreatorBridge(),"Android");setWebChromeClient(new WebChromeClient(){@Override public void onReceivedTitle(WebView v,String t){host.onTitle(t==null?"dumbNavigator":t);}@Override public void onProgressChanged(WebView v,int p){host.onProgress(p);}});setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(u.startsWith("dumb://")){go(u);return true;}return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("dumb".equalsIgnoreCase(u.getScheme()))return localResponse(u);return blocked();}});}
    public void go(String raw){String u=normalize(raw);if(u.isEmpty())return;if(!u.equals(current)){back.push(current);forward.clear();}current=u;host.onUrl(u);loadDumb(u);}
    public void backPage(){if(back.isEmpty())return;forward.push(current);current=back.pop();host.onUrl(current);loadDumb(current);} public void forwardPage(){if(forward.isEmpty())return;back.push(current);current=forward.pop();host.onUrl(current);loadDumb(current);} public boolean canGoBackDumb(){return !back.isEmpty();}public boolean canGoForwardDumb(){return !forward.isEmpty();}public String currentUrl(){return current;}
    private void loadDumb(String dumb){Uri u=Uri.parse(dumb);String h=u.getHost();if(h==null)return;String p=u.getPath();if(p==null||p.isEmpty())p="/";if(h.equals("uuu.une.developeit.dev")||h.equals("une.developeit.dev")){String a=assetPath(p);if(a!=null){String html=readAsset(a);if(html!=null){loadDataWithBaseURL(dumb,html,"text/html","UTF-8",null);return;}}}File root=new File(getContext().getFilesDir(),"dumb-sites/"+safe(h));File exact=new File(root,p.equals("/")?"index.html":p.substring(1));if(exact.exists()&&exact.isFile()){String html=readFile(exact);if(html!=null){loadDataWithBaseURL(dumb,html,"text/html","UTF-8",null);return;}}String[] ls=h.split("\\.");for(int i=1;i<ls.length-1;i++){String parent=String.join(".",Arrays.copyOfRange(ls,i,ls.length));File wild=new File(getContext().getFilesDir(),"dumb-sites/"+safe(parent)+"/wildcard/"+(p.equals("/")?"index.html":p.substring(1)));if(wild.exists()&&wild.isFile()){String html=readFile(wild);if(html!=null){loadDataWithBaseURL(dumb,html,"text/html","UTF-8",null);return;}}}String missing="<!doctype html><html><meta name='viewport' content='width=device-width,initial-scale=1'><body style='font-family:system-ui;background:#080b12;color:white;padding:32px'><h1>404</h1><p>La web <b>"+escape(h)+"</b> no existe dentro de dumbNavigator.</p></body></html>";loadDataWithBaseURL(dumb,missing,"text/html","UTF-8",null);}
    private WebResourceResponse localResponse(Uri u){String h=u.getHost();if(h==null)return blocked();String p=u.getPath();if(p==null||p.equals("/"))p="/index.html";if(h.equals("uuu.une.developeit.dev")||h.equals("une.developeit.dev")){String a=assetPath(p);if(a!=null)try{return response(mime(p),getContext().getAssets().open(a));}catch(Exception ignored){}}File f=new File(getContext().getFilesDir(),"dumb-sites/"+safe(h)+p);if(!f.exists()){String[]ls=h.split("\\.");for(int i=1;i<ls.length-1&&!f.exists();i++){String parent=String.join(".",Arrays.copyOfRange(ls,i,ls.length));f=new File(getContext().getFilesDir(),"dumb-sites/"+safe(parent)+"/wildcard"+p);}}if(!f.exists()||!f.isFile())return blocked();try{return response(mime(f.getName()),new FileInputStream(f));}catch(Exception e){return blocked();}}
    private String assetPath(String p){if(p.equals("/index.html"))return"developeit/index.html";if(p.equals("/new")||p.equals("/new/"))return"developeit/new/index.html";if(p.equals("/help")||p.equals("/help/"))return"developeit/help/index.html";if(p.equals("/about")||p.equals("/about/"))return"developeit/about/index.html";if(p.equals("/studio")||p.equals("/studio/"))return"developeit/studio/index.html";return null;}
    private static WebResourceResponse response(String type,InputStream in){return new WebResourceResponse(type,"UTF-8",in);}private static WebResourceResponse blocked(){return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}
    private static String mime(String n){n=n.toLowerCase(Locale.ROOT);if(n.endsWith(".css"))return"text/css";if(n.endsWith(".js"))return"application/javascript";if(n.endsWith(".json"))return"application/json";if(n.endsWith(".svg"))return"image/svg+xml";if(n.endsWith(".png"))return"image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return"image/jpeg";if(n.endsWith(".webp"))return"image/webp";return"text/html";}
    private static String normalize(String raw){if(raw==null||raw.trim().isEmpty())return"dumb://uuu.une.developeit.dev/";String s=raw.trim().toLowerCase(Locale.ROOT);if(!s.contains("://"))s="dumb://"+s;if(!s.startsWith("dumb://"))return"";Uri u=Uri.parse(s);String h=u.getHost();if(h==null)return"";String n=DumbDomains.publicInternalHost(h);if(n.isEmpty())return"";String p=u.getEncodedPath();if(p==null||p.isEmpty())p="/";return"dumb://"+n+p+(u.getEncodedQuery()==null?"":"?"+u.getEncodedQuery())+(u.getEncodedFragment()==null?"":"#"+u.getEncodedFragment());}
    private String readAsset(String p){try(InputStream in=getContext().getAssets().open(p)){return read(in);}catch(Exception e){return null;}}private static String readFile(File f){try(FileInputStream in=new FileInputStream(f)){return read(in);}catch(Exception e){return null;}}private static String read(InputStream in)throws Exception{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);return o.toString(StandardCharsets.UTF_8.name());}private static String safe(String h){return h.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9._-]","_");}private static String escape(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
    private final class CreatorBridge{@JavascriptInterface public void publish(String d,String h,boolean w){host.onPublish(d,h,w);}}
}
