plugins { id 'com.android.application' }

android {
    namespace 'dev.dumbnavigator'
    compileSdk 36
    defaultConfig {
        applicationId 'dev.dumbnavigator'
        minSdk 26
        targetSdk 36
        versionCode 10
        versionName '1.0.0-internal-browser'
    }
    buildTypes {
        debug { minifyEnabled false; debuggable true }
        release { minifyEnabled true; shrinkResources true; debuggable false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
