plugins { id 'com.android.application' }

android {
    namespace 'dev.dumbnavigator'
    compileSdk 36
    defaultConfig {
        applicationId 'dev.dumbnavigator'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '0.4.0-internal-chromium'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
